import type { Product, ProductAlternative } from './types/product.js';
import { createProductScore } from './scoring.js';

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'tn-harissa-sicam',
    barcode: '6194001900123',
    name: 'Harissa Berbère Pur Piment',
    brand: 'SICAM',
    category: 'Condiments & Sauces',
    origin: 'Cap Bon, Tunisie',
    isLocal: true,
    isBio: true,
    image: '/assets_v2/product_harissa_jar.png',
    score: createProductScore(83, 85, 80, 95),
    nutrition: {
      servingSize: '100g',
      energyKcal: 72,
      sugars: 2.1,
      saturatedFat: 0.4,
      salt: 1.2,
      fiber: 4.8,
      proteins: 2.9,
    },
    additives: [],
    ingredientsSummary: 'Piments rouges séchés, ail de Medjez el Bab, coriandre, carvi, sel marin.',
  },
  {
    id: 'tn-huile-ruspina',
    barcode: '6194002400456',
    name: "Huile d'Olive Vierge Extra",
    brand: 'Ruspina',
    category: 'Huiles & Matières grasses',
    origin: 'Sahel, Tunisie',
    isLocal: true,
    isBio: true,
    image: '/assets_v2/product_olive_oil.jpg',
    score: createProductScore(92, 94, 90, 98),
    nutrition: {
      servingSize: '100ml',
      energyKcal: 824,
      sugars: 0,
      saturatedFat: 14.0,
      salt: 0,
      fiber: 0,
      proteins: 0,
    },
    additives: [],
    ingredientsSummary: "100% Huile d'olive vierge extra de première pression à froid.",
  },
  {
    id: 'tn-yaourt-delice',
    barcode: '6194003300789',
    name: 'Yaourt Brassé Nature',
    brand: 'Délice Danone',
    category: 'Produits Laitiers',
    origin: 'Soliman, Tunisie',
    isLocal: true,
    isBio: false,
    image: '/assets_v2/product_delice_yogurt.jpg',
    score: createProductScore(58, 62, 52, 92),
    nutrition: {
      servingSize: '100g',
      energyKcal: 62,
      sugars: 4.7,
      saturatedFat: 2.1,
      salt: 0.1,
      proteins: 3.8,
    },
    additives: [
      {
        code: 'E440',
        nameFr: 'Pectine',
        nameAr: 'بكتين',
        risk: 'safe',
        functionCategory: 'Épaississant',
      },
      {
        code: 'E330',
        nameFr: 'Acide citrique',
        nameAr: 'حمض الستريك',
        risk: 'safe',
        functionCategory: 'Correcteur d\'acidité',
      },
    ],
    ingredientsSummary: 'Lait entier pasteurisé, ferments lactiques vivants, pectine.',
  },
  {
    id: 'tn-soda-boga',
    barcode: '6194004500999',
    name: 'Boisson Gazeuse Cidre',
    brand: 'Boga',
    category: 'Boissons & Sodas',
    origin: 'Tunis, Tunisie',
    isLocal: true,
    isBio: false,
    image: '/assets_v2/product_boga_cidre.jpg',
    score: createProductScore(22, 18, 28, 96),
    nutrition: {
      servingSize: '100ml',
      energyKcal: 44,
      sugars: 10.8,
      saturatedFat: 0,
      salt: 0.02,
    },
    additives: [
      {
        code: 'E150d',
        nameFr: 'Caramel au sulfite d\'ammonium',
        nameAr: 'كراميل الكبريتيت',
        risk: 'moderate',
        functionCategory: 'Colorant',
      },
      {
        code: 'E338',
        nameFr: 'Acide phosphorique',
        nameAr: 'حمض الفوسفوريك',
        risk: 'moderate',
        functionCategory: 'Acidifiant',
      },
      {
        code: 'E211',
        nameFr: 'Benzoate de sodium',
        nameAr: 'بنزوات الصوديوم',
        risk: 'moderate',
        functionCategory: 'Conservateur',
      },
    ],
    ingredientsSummary: 'Eau gazéifiée, sucre, colorant caramel E150d, acidifiant E338, arôme naturel cidre.',
  },
  {
    id: 'tn-biscuits-bimo',
    barcode: '6194005100112',
    name: 'Biscuits Choco Fourrés',
    brand: 'BIMO',
    category: 'Biscuits & Snacks',
    origin: 'Mégrine, Tunisie',
    isLocal: true,
    isBio: false,
    image: '/assets_v2/product_bimo_choco.jpg',
    score: createProductScore(34, 30, 40, 91),
    nutrition: {
      servingSize: '100g',
      energyKcal: 485,
      sugars: 32.0,
      saturatedFat: 9.5,
      salt: 0.6,
      proteins: 6.2,
    },
    additives: [
      {
        code: 'E500',
        nameFr: 'Carbonates de sodium',
        nameAr: 'كربونات الصوديوم',
        risk: 'safe',
        functionCategory: 'Poudre à lever',
      },
      {
        code: 'E322',
        nameFr: 'Lécithine de soja',
        nameAr: 'ليسيثين الصويا',
        risk: 'safe',
        functionCategory: 'Émulsifiant',
      },
    ],
    ingredientsSummary: 'Farine de blé, sucre, matière grasse végétale hydrogénée, cacao maigre, poudre à lever.',
  },
  {
    id: 'tn-sables-warda',
    barcode: '6194006200334',
    name: 'Sablés Pur Beurre Artisanal',
    brand: 'Warda Terroir',
    category: 'Biscuits & Pâtisseries',
    origin: 'Sfax, Tunisie',
    isLocal: true,
    isBio: true,
    image: '/assets_v2/product_warda_sables.jpg',
    score: createProductScore(74, 72, 78, 93),
    nutrition: {
      servingSize: '100g',
      energyKcal: 410,
      sugars: 14.5,
      saturatedFat: 4.8,
      salt: 0.2,
      fiber: 3.1,
      proteins: 7.5,
    },
    additives: [],
    ingredientsSummary: 'Farine complète tunisienne, beurre frais de ferme, sucre de canne brut, vanille naturelle.',
  },
];

export const SEED_ALTERNATIVES: ProductAlternative[] = [
  {
    originalProductId: 'tn-biscuits-bimo',
    betterProduct: SEED_PRODUCTS[5], // Warda Sablés (74 vs 34)
    gainScore: 40,
    reasonFr: 'Moins de sucre raffiné, sans graisse végétale hydrogénée et sans additif de synthèse.',
    reasonAr: 'أقل سكر، دهون حيوانية طبيعية وبدون مواد حافظة أو زيوت مهدرجة.',
  },
  {
    originalProductId: 'tn-soda-boga',
    betterProduct: SEED_PRODUCTS[0], // Harissa or Fresh Citronnade
    gainScore: 61,
    reasonFr: 'Privilégiez les boissons naturelles ou citronnade artisanale tunisienne sans colorants chimiques.',
    reasonAr: 'من الأفضل اختيار عصير ليمون تونسي طبيعي بدون ملونات كيميائية E150d.',
  },
];
