import type { Product, ProductAlternative } from './types/product.js';
import { createProductScore } from './scoring.js';

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'tn-harissa-sicam',
    barcode: '6194001900123',
    name: 'Harissa Berbère Pur Piment',
    brand: 'SICAM',
    category: 'Condiments & Sauces',
    origin: 'Cap Bon, Tunisie',
    isLocal: true,
    isBio: true,
    image: '/assets_v2/product_harissa_jar.png',
    score: createProductScore(83, 85, 80, 95),
    nutriScore: 'a',
    novaGroup: 1,
    nutrition: {
      servingSize: '100g',
      energyKcal: 72,
      sugars: 2.1,
      saturatedFat: 0.4,
      salt: 1.2,
      fiber: 4.8,
      proteins: 2.9,
    },
    additives: [],
    allergens: [],
    ingredientsSummary: 'Piments rouges séchés, ail de Medjez el Bab, coriandre, carvi, sel marin.',
  },
  {
    id: 'tn-huile-ruspina',
    barcode: '6194002400456',
    name: "Huile d'Olive Vierge Extra",
    brand: 'Ruspina',
    category: 'Huiles & Matières grasses',
    origin: 'Sahel, Tunisie',
    isLocal: true,
    isBio: true,
    image: '/assets_v2/product_olive_oil.jpg',
    score: createProductScore(92, 94, 90, 98),
    nutriScore: 'c', // Olive oil standard Nutri-Score is C due to pure fat, but score is 92/100 due to healthy polyphenols
    novaGroup: 1,
    nutrition: {
      servingSize: '100ml',
      energyKcal: 824,
      sugars: 0,
      saturatedFat: 14.0,
      salt: 0,
      fiber: 0,
      proteins: 0,
    },
    additives: [],
    allergens: [],
    ingredientsSummary: "100% Huile d'olive vierge extra tunisienne de première pression à froid.",
  },
  {
    id: 'tn-couscous-epi',
    barcode: '6194007100888',
    name: 'Couscous Fin Pur Blé Dur',
    brand: "L'Épi d'Or",
    category: 'Pâtes & Céréales',
    origin: 'Sousse, Tunisie',
    isLocal: true,
    isBio: false,
    image: '/assets_v2/product_warda_sables.jpg',
    score: createProductScore(88, 90, 85, 96),
    nutriScore: 'a',
    novaGroup: 1,
    nutrition: {
      servingSize: '100g',
      energyKcal: 355,
      sugars: 1.8,
      saturatedFat: 0.3,
      salt: 0.01,
      fiber: 5.2,
      proteins: 12.5,
    },
    additives: [],
    allergens: ['Gluten'],
    ingredientsSummary: 'Semoule de blé dur de qualité supérieure, eau.',
  },
  {
    id: 'tn-dattes-oasis',
    barcode: '6194008200555',
    name: 'Dattes Branchées Deglet Nour',
    brand: 'Oasis Tozeur',
    category: 'Fruits & Terroir',
    origin: 'Tozeur, Tunisie',
    isLocal: true,
    isBio: true,
    image: '/assets_v2/product_delice_yogurt.jpg',
    score: createProductScore(94, 95, 92, 99),
    nutriScore: 'a',
    novaGroup: 1,
    nutrition: {
      servingSize: '100g',
      energyKcal: 282,
      sugars: 63.4, // Sucre naturel du fruit
      saturatedFat: 0.1,
      salt: 0.01,
      fiber: 8.0,
      proteins: 2.5,
    },
    additives: [],
    allergens: [],
    ingredientsSummary: '100% Dattes naturelles branchées de l\'oasis de Tozeur sans sirop ajouté.',
  },
  {
    id: 'tn-thon-elmanar',
    barcode: '6194009300666',
    name: "Thon Entier à l'Huile d'Olive",
    brand: 'El Manar',
    category: 'Conserves de Poissons',
    origin: 'Zarzis, Tunisie',
    isLocal: true,
    isBio: false,
    image: '/assets_v2/product_harissa_jar.png',
    score: createProductScore(86, 88, 82, 94),
    nutriScore: 'b',
    novaGroup: 3,
    nutrition: {
      servingSize: '100g',
      energyKcal: 210,
      sugars: 0,
      saturatedFat: 2.8,
      salt: 0.9,
      fiber: 0,
      proteins: 26.0,
    },
    additives: [],
    allergens: ['Poisson'],
    ingredientsSummary: 'Thon blanc (Thunnus alalunga), huile d\'olive vierge, sel marin.',
  },
  {
    id: 'tn-sables-warda',
    barcode: '6194006200334',
    name: 'Sablés Pur Beurre Artisanal',
    brand: 'Warda Terroir',
    category: 'Biscuits & Pâtisseries',
    origin: 'Sfax, Tunisie',
    isLocal: true,
    isBio: true,
    image: '/assets_v2/product_warda_sables.jpg',
    score: createProductScore(74, 72, 78, 93),
    nutriScore: 'c',
    novaGroup: 3,
    nutrition: {
      servingSize: '100g',
      energyKcal: 410,
      sugars: 14.5,
      saturatedFat: 4.8,
      salt: 0.2,
      fiber: 3.1,
      proteins: 7.5,
    },
    additives: [],
    allergens: ['Gluten', 'Lait'],
    ingredientsSummary: 'Farine complète tunisienne, beurre frais de ferme, sucre de canne brut, vanille naturelle.',
  },
  {
    id: 'tn-yaourt-delice',
    barcode: '6194003300789',
    name: 'Yaourt Brassé Nature',
    brand: 'Délice Danone',
    category: 'Produits Laitiers',
    origin: 'Soliman, Tunisie',
    isLocal: true,
    isBio: false,
    image: '/assets_v2/product_delice_yogurt.jpg',
    score: createProductScore(58, 62, 52, 92),
    nutriScore: 'b',
    novaGroup: 3,
    nutrition: {
      servingSize: '100g',
      energyKcal: 62,
      sugars: 4.7,
      saturatedFat: 2.1,
      salt: 0.1,
      proteins: 3.8,
    },
    additives: [
      {
        code: 'E440',
        nameFr: 'Pectine',
        nameAr: 'بكتين',
        risk: 'safe',
        functionCategory: 'Épaississant naturel',
        descriptionFr: 'Gélifiant végétal extrait de pépins de pommes ou d\'agrumes, inoffensif pour la santé.',
        descriptionAr: 'مستخلص نباتي طبيعي لتكثيف القوام، آمن على الصحة.',
      },
      {
        code: 'E330',
        nameFr: 'Acide citrique',
        nameAr: 'حمض الستريك',
        risk: 'safe',
        functionCategory: 'Correcteur d\'acidité',
        descriptionFr: 'Régulateur d\'acidité naturellement présent dans le citron, sans danger avéré.',
        descriptionAr: 'معدل حموضة طبيعي موجود في الليمون، لا يشكل خطورة.',
      },
    ],
    allergens: ['Lait'],
    ingredientsSummary: 'Lait entier pasteurisé, ferments lactiques vivants, pectine, acide citrique.',
  },
  {
    id: 'tn-fromage-landor',
    barcode: '6194004100222',
    name: 'Fromage Carré Toast Fondu',
    brand: "Land'Or",
    category: 'Fromages Fondus',
    origin: 'Bou Argoub, Tunisie',
    isLocal: true,
    isBio: false,
    image: '/assets_v2/product_delice_yogurt.jpg',
    score: createProductScore(38, 32, 45, 90),
    nutriScore: 'd',
    novaGroup: 4,
    nutrition: {
      servingSize: '100g',
      energyKcal: 275,
      sugars: 3.8,
      saturatedFat: 14.5,
      salt: 2.3,
      proteins: 11.0,
    },
    additives: [
      {
        code: 'E452',
        nameFr: 'Polyphosphates',
        nameAr: 'بوليفوسفات',
        risk: 'moderate',
        functionCategory: 'Sels de fonte',
        descriptionFr: 'Additif émulsifiant phosphaté pouvant perturber l\'absorption du calcium en consommation fréquente.',
        descriptionAr: 'أملاح تذويب صناعية قد تؤثر على امتصاص الكالسيوم مع الاستهلاك المفرط.',
      },
      {
        code: 'E160a',
        nameFr: 'Bêta-carotène',
        nameAr: 'بيتا كاروتين',
        risk: 'safe',
        functionCategory: 'Colorant naturel',
        descriptionFr: 'Colorant orange extrait de végétaux.',
        descriptionAr: 'ملون برتقالي نباتي آمن.',
      },
    ],
    allergens: ['Lait'],
    ingredientsSummary: 'Fromages, eau, beurre, protéines de lait, sels de fonte E452, colorant E160a.',
  },
  {
    id: 'tn-biscuits-bimo',
    barcode: '6194005100112',
    name: 'Biscuits Choco Fourrés',
    brand: 'BIMO',
    category: 'Biscuits & Snacks',
    origin: 'Mégrine, Tunisie',
    isLocal: true,
    isBio: false,
    image: '/assets_v2/product_bimo_choco.jpg',
    score: createProductScore(34, 30, 40, 91),
    nutriScore: 'e',
    novaGroup: 4,
    nutrition: {
      servingSize: '100g',
      energyKcal: 485,
      sugars: 32.0,
      saturatedFat: 9.5,
      salt: 0.6,
      proteins: 6.2,
    },
    additives: [
      {
        code: 'E500',
        nameFr: 'Carbonates de sodium',
        nameAr: 'كربونات الصوديوم',
        risk: 'safe',
        functionCategory: 'Poudre à lever',
        descriptionFr: 'Bicarbonate de soude utilisé pour la levée de pâte, sans risque pour la santé.',
        descriptionAr: 'خميرة كيميائية كربونات الصوديوم آمنة.',
      },
      {
        code: 'E322',
        nameFr: 'Lécithine de soja',
        nameAr: 'ليسيثين الصويا',
        risk: 'safe',
        functionCategory: 'Émulsifiant',
        descriptionFr: 'Émulsifiant d\'origine végétale permettant de lier l\'huile et l\'eau.',
        descriptionAr: 'مستحلب نباتي مستخرج من فول الصويا.',
      },
    ],
    allergens: ['Gluten', 'Soja'],
    ingredientsSummary: 'Farine de blé, sucre, matière grasse végétale hydrogénée, cacao maigre, poudre à lever.',
  },
  {
    id: 'tn-soda-boga',
    barcode: '6194004500999',
    name: 'Boisson Gazeuse Cidre',
    brand: 'Boga',
    category: 'Boissons & Sodas',
    origin: 'Tunis, Tunisie',
    isLocal: true,
    isBio: false,
    image: '/assets_v2/product_boga_cidre.jpg',
    score: createProductScore(22, 18, 28, 96),
    nutriScore: 'e',
    novaGroup: 4,
    nutrition: {
      servingSize: '100ml',
      energyKcal: 44,
      sugars: 10.8,
      saturatedFat: 0,
      salt: 0.02,
    },
    additives: [
      {
        code: 'E150d',
        nameFr: 'Caramel au sulfite d\'ammonium',
        nameAr: 'كراميل الكبريتيت',
        risk: 'moderate',
        functionCategory: 'Colorant de synthèse',
        descriptionFr: 'Colorant chimique brun foncé soupçonné de contenir des résidus de composés indésirables (4-MEI).',
        descriptionAr: 'ملون كيميائي بني غامق يحتوي على شوائب كيميائية يفضل تفاديها.',
      },
      {
        code: 'E338',
        nameFr: 'Acide phosphorique',
        nameAr: 'حمض الفوسفوريك',
        risk: 'moderate',
        functionCategory: 'Acidifiant minéral',
        descriptionFr: 'Acidifiant puissant lié à l\'érosion de l\'émail dentaire et à la déminéralisation.',
        descriptionAr: 'حمض صناعي قوي قد يضر بمينا الأسنان وتوازن المعادن.',
      },
      {
        code: 'E211',
        nameFr: 'Benzoate de sodium',
        nameAr: 'بنزوات الصوديوم',
        risk: 'moderate',
        functionCategory: 'Conservateur',
        descriptionFr: 'Conservateur chimique déconseillé chez les personnes sensibles et asthmatiques.',
        descriptionAr: 'مادة حافظة كيميائية قد تسبب حساسية لدى بعض الأشخاص.',
      },
    ],
    allergens: [],
    ingredientsSummary: 'Eau gazéifiée, sucre, colorant caramel E150d, acidifiant E338, conservateur E211, arôme cidre.',
  },
];

export const SEED_ALTERNATIVES: ProductAlternative[] = [
  {
    originalProductId: 'tn-biscuits-bimo',
    betterProduct: SEED_PRODUCTS[5], // Warda Sablés (74 vs 34)
    gainScore: 40,
    reasonFr: 'Moins de sucre raffiné, beurre frais au lieu de graisse végétale hydrogénée et sans additif chimique.',
    reasonAr: 'أقل سكر، زبدة طبيعية بدل الزيوت المهدرجة وخالي من المواد المضافة الصناعية.',
  },
  {
    originalProductId: 'tn-soda-boga',
    betterProduct: SEED_PRODUCTS[0], // Harissa or traditional fresh juice
    gainScore: 61,
    reasonFr: 'Privilégiez les boissons naturelles ou citronnade artisanale tunisienne sans colorant E150d ni acide phosphorique.',
    reasonAr: 'من الأفضل اختيار عصير ليمون تونسي طبيعي بدون ملونات كيميائية E150d أو أحماض صناعية.',
  },
  {
    originalProductId: 'tn-fromage-landor',
    betterProduct: SEED_PRODUCTS[2], // Yaourt or fresh ricotta/sicilien
    gainScore: 20,
    reasonFr: 'Remplacez les fromages fondus ultra-transformés par des yaourts natures ou des fromages frais traditionnels (Ricotta, Sicilien).',
    reasonAr: 'عوض الجبن المطبوخ بالياغورت الطبيعي أو الريكوتا التونسية الطازجة الخالية من أملاح التذويب.',
  },
];
